intelligent_tools.settings:
  label: 'Intelligent Tools settings'
  type: config_object
  mapping:
    intelligent_tools_content:
      type: string
      label: 'Content Type(auto tag)'
    intelligent_tools_field:
      type: string
      label: 'Field from(auto tag)'
    intelligent_tools_field_to:
      type: string
      label: 'Field to'
    intelligent_tools_text_summarize_content:
      type: string
      label: 'Content Type(text summarize)'
    intelligent_tools_text_summarize_field:
      type: string
      label: 'Field from(text summarize)'
    intelligent_tools_duplicate_rate_content:
      type: string
      label: 'Content Type(duplicate rate)'
    intelligent_tools_duplicate_rate_field:
      type: string
      label: 'Field from(duplicate rate)'
    intelligent_tools_ip:
      type: string
      label: IP address(auto tag)
    intelligent_tools_text_summarize_ip:
      type: string
      label: IP address(text summarize)
    intelligent_tools_duplicate_rate_ip:
      type: string
      label: IP address(duplicate rate)
    intelligent_tools_tags:
      type: string
      label: Number of Tags
